# api local config
spring:
  config:
    activate:
      on-profile: dev
  messages:
    basename: messages/messages
    encoding: UTF-8
  datasource:
   url: jdbc:mysql://34.64.92.3:3306/kickalert
   username: admin
   password: admin
   driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:mysql://libl-aurora-mysql8-db-dev.cluster-cshrhqgio6er.ap-northeast-2.rds.amazonaws.com/libl
#    username: admin
#    password: Libl!23$0
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# logging 설정
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
